### ISSUE TITLE
菜单栏 会一直超过灰色区域是什么问题

### ISSUE THREAD

**Issue by wesleyxiao** [best-flutter/flutter_dropdown_menu#1]
simulator: iphone x

左边菜单栏和邮编菜单栏 下拉的时候 有的时候会正常， 但是大多数的时候 在灰色区域会看得见下面的菜单选项。

还有就是 菜单收起来的时候，灰色区域没有了，菜单还是会在不会消失。

![img_2199](https://user-images.githubusercontent.com/2177367/43590436-fbac73ca-963e-11e8-8cbe-3dc74c21c3b9.png)
![img_2200](https://user-images.githubusercontent.com/2177367/43590439-fc7641e6-963e-11e8-853e-672fd72cc109.png)
![img_2201](https://user-images.githubusercontent.com/2177367/43590440-fc8bbb8e-963e-11e8-8bf7-add830114707.png)

**Comment by jzoom** [comment]
ListView在Row里面估计有点问题，现在加了个RectClipper解决了
